import type { InitialArtifacts } from '@/features/agents/lib/editor-state';

export interface CodeRepositoryInput {
  projectTitle: string;
  projectPrompt: string;
  artifacts: InitialArtifacts;
  version?: number | 'latest';
}

export interface SplitHtmlResult {
  indexHtml: string;
  stylesCss?: string;
  appJs?: string;
}

/**
 * 从完整 HTML 中拆分内联 style / script，便于作为多文件仓库导出。
 */
export function splitHtmlDocument(html: string): SplitHtmlResult {
  let indexHtml = html;
  let stylesCss: string | undefined;
  let appJs: string | undefined;

  const styleMatch = html.match(/<style[^>]*>([\s\S]*?)<\/style>/i);
  if (styleMatch) {
    stylesCss = styleMatch[1].trim();
    indexHtml = indexHtml.replace(styleMatch[0], '<link rel="stylesheet" href="styles.css" />');
  }

  const scriptMatch = indexHtml.match(/<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/i);
  if (scriptMatch) {
    appJs = scriptMatch[1].trim();
    indexHtml = indexHtml.replace(
      scriptMatch[0],
      '<script src="app.js"></script>',
    );
  }

  return { indexHtml, stylesCss, appJs };
}

/**
 * 生成 README，说明需求与本地运行方式。
 */
function buildReadme(input: CodeRepositoryInput): string {
  const versionLabel =
    input.version && input.version !== 'latest' ? `v${input.version}` : 'latest';

  return `# ${input.projectTitle}

由 AtomForge 生成的应用代码仓库（${versionLabel}）。

## 原始需求

${input.projectPrompt}

## 目录结构

- \`public/\` — 可运行的前端应用
- \`docs/\` — 计划、PRD、架构设计等 Agent 产物

## 本地运行

\`\`\`bash
npm install
npm run dev
\`\`\`

浏览器访问 http://localhost:4173

## 说明

- 接入 OpenAI API Key 后，Alex 可生成更完整的多文件项目结构
- 当前 Demo 模式下导出的是 Agent 团队协作产出的代码与文档
`;
}

/**
 * 生成静态站点项目的 package.json。
 */
function buildPackageJson(projectTitle: string): string {
  const name =
    projectTitle
      .toLowerCase()
      .replace(/[^\w\u4e00-\u9fa5-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48) || 'atomforge-app';

  return JSON.stringify(
    {
      name,
      private: true,
      version: '0.1.0',
      description: 'Generated by AtomForge',
      scripts: {
        dev: 'npx serve public -l 4173',
        start: 'npx serve public -l 4173',
        preview: 'npx serve public -l 4173',
      },
    },
    null,
    2,
  );
}

/**
 * 将 Agent 产物组装为代码仓库文件映射（路径 → 内容）。
 */
export function buildCodeRepositoryFiles(
  input: CodeRepositoryInput,
): Record<string, string> {
  const { artifacts, projectTitle, projectPrompt } = input;
  const code = artifacts.code;

  if (!code?.trim()) {
    throw new Error('暂无可导出的代码，请先完成构建');
  }

  const files: Record<string, string> = {
    'README.md': buildReadme(input),
    'package.json': buildPackageJson(projectTitle),
    '.gitignore': ['node_modules/', '.DS_Store', '*.log'].join('\n'),
  };

  if (artifacts.plan) {
    files['docs/plan.md'] = artifacts.plan;
  }
  if (artifacts.prd) {
    files['docs/PRD.md'] = artifacts.prd;
  }
  if (artifacts.architecture) {
    files['docs/architecture.md'] = artifacts.architecture;
  }

  files['docs/prompt.txt'] = projectPrompt;

  const { indexHtml, stylesCss, appJs } = splitHtmlDocument(code);
  files['public/index.html'] = indexHtml;
  if (stylesCss) {
    files['public/styles.css'] = stylesCss;
  }
  if (appJs) {
    files['public/app.js'] = appJs;
  }

  return files;
}

/**
 * 规范化 zip 根目录名。
 */
export function sanitizeRepoDirName(title: string): string {
  return title.replace(/[^\w\u4e00-\u9fa5-]/g, '-').replace(/^-+|-+$/g, '') || 'atomforge-app';
}
